fix image share check
moevm/document_insight_system pull request #454
Opened 2023-07-04 12:34 UTC by MarinaProsche

Добавлены функии получения высоты страницы (файла pdf) и суммы высот изображений (файла pdf) в
app/main/reports/pdf_document/pdf_document_manager.py

2023-07-30 18:09 UTC, HadronCollider requested changes

2023-07-30 18:09 UTC, HadronCollider commented on app/main/checks/report_checks/image_share_check.py
>      def check(self):
С этой проверкой (или скорее в содержимом отчета) есть два момента
- `self.page_count` файла, который заполняется как `self.page_count = len(self.pages)` - это кол-во страниц во всем отчете (включая приложения, которые мы не должны учитывать)
    - для подсчета кол-ва страниц без учета приложения есть `self.file.page_counter()` (там по регулярке ищется страницы с `ПРИЛОЖЕНИЕ ...` - возможно, можно улучшить) -   https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/master/app/main/reports/docx_uploader/docx_uploader.py#L195
- опять возвращаясь к приложениям- изображения могут быть в приложениях (в них кол-во изображений не регламентировано и нами не отслеживается - пусть хоть одни фотки понаставляют) - поэтому надо как-то исключить изображения из приложений и не считать их в `page_images`

2023-07-30 18:09 UTC, HadronCollider commented on app/main/reports/pdf_document/pdf_document_manager.py
> +            self.pdf_fitz = fitz.open(convert_to(path_to_file, target_format='pdf'))
Для раза конвертировать (для pdfplumber и fitz) - излишне, `convert_to` возвращает путь к файлу - так что его можно переиспользовать

P.S. а можем ли мы свести всё к fitz? или чего он не умеет такого, что умеет plumber, что мы не сможем избавиться от `self.pdf_file = pdfplumber` (или они вообще там друг на друге завязаны и зависимы)

2023-07-30 18:09 UTC, HadronCollider commented on app/main/reports/pdf_document/pdf_document_manager.py
> +        top_margin = page_rect.y0
маленькие прелести python в области присваивания (для экономии места/строк):
```python3
height, top_margin = page_rect.height, page_rect.y0
```

2023-08-01 13:53 UTC, MarinaProsche commented
Исправила.
-- изменила подчсет страниц в проверке (до приложения)
-- избавилась от pdf_plumber (пока на всякий случай закомментировала), пришлось изменить имена нескольких переменных и, как следствие, коды проверок.

https://github.com/moevm/mse_auto_checking_slides_vaganov/commit/5523f0a4b12941e66d830e1c9f054ac27955b643

2024-04-23 23:54 UTC, HadronCollider approved these changes

2024-04-23 23:55 UTC, merged