451 message about point
moevm/document_insight_system pull request #457
Opened 2023-07-17 10:13 UTC by MarinaProsche

Изменен файл "results.html", добавлено сообщение для студентов в соответствии с задачей.
Сообщение о статусе "Допущен" появляется когда score = 1
Сообщение о минимальном бале прохождения, когда 0.5 < score < 1
Если score < 0.5 сообщение о минимальном балле отсутствует, проверка не пройдена.

2023-07-19 08:51 UTC, zmm commented on app/templates/results.html
> +                Это повысит ваш допуск до уровня <b>"Допущен"</b>.
Нужно более общее решение - необходимо хранить и сами наборы, и баллы-пороги для них в БД рядом с записью соответсвующей задачи (набора критериев). 
То есть, это должны быть не захардкоженные одинаковые сообщения для всех задач, а кастомизируемые (индивидуальные) сообщения под каждую задачу.
Если для задачи такое не задано, то ничего не отображаем.

2023-07-28 09:35 UTC, MarinaProsche commented
Сделала более общее решение. Добавила в базу словарь пока с произвольными значениями "score" и соответствующими им сообщениями

https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/457/commits/99df8c84f2f05926d024652d92ce2af2dc9ce79e

2023-07-28 12:19 UTC, MarinaProsche commented
Исправила.

fcf5945b694223c430784cadc4653bf656c0de80

2023-07-30 18:40 UTC, HadronCollider requested changes
Пока не запускал, но комментарии следующие:
- point_levels - должны быть порогами, а не точными значениями баллов (про логику `get_point_levels(self)`)
- добавьте редактирование point_levels критерия на клиенте (что-то вроде второго поля на странице редактирования критерия
    - можно задавать в текстовом поле как json  (аналогично списку критериев)
    - задача со звездочкой - чтобы сильно не удлинять страницу редактирования критерия - сделать в UI что-то вроде вкладок (на одной вкладке - редактируем критерии, переключаемся на вторую вкладку - редактируем поинты) - раньше с таким не работал, но подозреваю, что решения есть (и выглядит это по идее опрятно)
```
[
    [порог1, сообщение1],
    [порог2, сообщение2],
]
````

2023-08-11 13:55 UTC, thehighestmath commented on app/main/check_packs/pack_config.py
> +                'Уровень Вашего допуска "Допущен"': [0.999, ]
`if value[0] < self.score < value[1]:`
Разве тут не будет IndexError на этом уровне допуска?

2023-08-11 13:55 UTC, thehighestmath commented on app/db/db_types.py
> +            if value[0] < self.score < value[1]:
может какую-то границу надо включить? (не уверен)

2023-08-11 13:55 UTC, thehighestmath commented on app/db/db_types.py
> +    def get_point_levels(self):
функция иногда возвращает `None` не лучше ли поднимать исключение?

2023-08-11 13:55 UTC, thehighestmath commented on assets/styles/criteria.css
> +}
пустая строка в конце файла?

2023-08-12 10:22 UTC, MarinaProsche commented
Исправила все замечания, кроме необходимости границ.
Также исправила баг с отображением point_levels в json

2025-04-11 08:37 UTC, closed without merging