466 criteria pack for md test
moevm/document_insight_system pull request #471
Opened 2023-10-30 08:45 UTC by MarinaProsche

В продолжение (копия) #465 
Ветка для проверки работоспособности нового пакета

2024-02-20 13:40 UTC, HadronCollider commented
Можно, пожалуйста, пример набора критериев для проверки? (в формате для https://slides-checker.moevm.info/criterion_pack)

2024-02-20 14:16 UTC, MarinaProsche commented
@HadronCollider Дмитрий, уточните, пожалуйста, в таком формате:

[
    [
        "simple_check"
    ],
    [
        "banned_words_in_literature"
    ],
    [
        "page_counter"
    ],
    [
        "short_sections_check"
    ],
    [
        "banned_words_check"
    ],
    [
        "right_words_check"
    ],
    [
        "banned_words_in_literature"
    ],
    [
        "literature_references"
    ],
    [
        "image_references"
    ],
    [
        "table_references"
    ],
    [
        "first_pages_check"
    ],
    [
        "main_character_check"
    ],
    [
        "needed_headers_check"
    ],
    [
        "report_section_component"
    ],
    [
        "spelling_check"
    ]
]

2024-03-10 00:04 UTC, HadronCollider requested changes
Из того, что не отмечено в комментариях к коду
- если нет таблиц / рисунков / списка литературы - занулять результаты критерия точно не нужно (как минимум, в работах с MD их может не быть, а мы ставим студентам 0), аналогично с ВКР -- возможно, это недосмотр с административной стороны прошлого года, но все-таки кажется, что в случае отсутствия критерий тривиально пройден
- стоит уменьшить (или контролировать) "размеры" выводимой структуры в критерии проверки наличия разделов - для md там, по-видимому, вставляются "сырые" названия в html-формате (с h1, h2, etc) - в итоге браузер текст интерпретирует как html и там большушие заголовки - такое нам не надо (но надо отслеживать какой заголовок какого уровня - возможно, с помощью отступов)

2024-03-11 17:01 UTC, MarinaProsche commented on app/main/reports/md_uploader/md_uploader.py
> +    def page_counter(self):
Сейчас этот подсчет нужен для того, чтобы открывать в качестве ссылки страницу со списком литературы в проверке источников (обсуждали в переписке). Удалить?

2024-03-11 17:01 UTC, MarinaProsche commented on app/main/reports/md_uploader/md_uploader.py
> +        self.count = 0
Исправила

2024-03-11 17:02 UTC, MarinaProsche commented on app/main/reports/md_uploader/md_uploader.py
> +class MdUpload(DocumentUploader):
Исправила

2024-03-11 17:06 UTC, MarinaProsche commented on app/main/reports/md_uploader/md_uploader.py
> +        html_text = html_text.replace("<li>", "").replace("</li>", "").replace("</ol>", "").replace("<ol>", "")
Пока выглядит, как будто мы сделали хорошо, потому что в некоторых документах (не всех, что тоже придает хаоса) при парсинге тэги сохраняются в отдельные строки, а это как раз приводит к некорректным проверкам

2024-03-11 17:29 UTC, MarinaProsche commented on app/utils/check_file.py
> +    return "ok"
Исправила

2024-03-12 07:41 UTC, MarinaProsche commented on app/main/checks/report_checks/table_references.py
> +                detected_references = re.findall(r'таблиц[аеыу][\d .]+', self.file.paragraphs[i].paragraph_text)
Оставила "paragraph_text"

2024-03-12 07:41 UTC, MarinaProsche commented on app/main/checks/report_checks/literature_references.py
> +                detected_references = re.findall(r'\[[\d \-,]+\]', self.file.paragraphs[i].to_string().split('\n')[1])
Исправила на "paragraph_text", работает корректно

2024-03-12 07:44 UTC, MarinaProsche commented on app/main/checks/report_checks/literature_references.py
> +                            array_of_references.add(int(one_part))
Исправила

2024-03-12 07:54 UTC, MarinaProsche commented on app/main/checks/report_checks/literature_references.py
> +            if isinstance(self.file.paragraphs[i], str):
Исправила, работает корректно

2024-03-12 14:08 UTC, MarinaProsche commented on app/main/reports/docx_uploader/docx_uploader.py
> +                if re.search('СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ', line.strip()):
Исправлено на более широкое выпажение:
'список[ \t]*(использованных|использованной|)[ \t]*(источников|литературы)', line.strip().lower()

2024-03-13 12:13 UTC, HadronCollider commented on app/main/reports/md_uploader/md_uploader.py
> +    def page_counter(self):
Давайте пометим на будущее комментарием в коде, что/зачем происходит - чтобы не забыть

2024-03-13 18:52 UTC, HadronCollider approved these changes

2024-03-16 17:39 UTC, merged