423 max abstract
moevm/document_insight_system pull request #478
Opened 2023-11-26 21:26 UTC by TheAnton1

2023-11-27 12:25 UTC, HadronCollider requested changes

2023-11-27 12:25 UTC, HadronCollider commented on app/main/checks/report_checks/max_abstract_size_check.py
> +        self.max_size = 1
Размер стоит вынести в аргументы конструктора (= критерия)

2023-11-27 12:25 UTC, HadronCollider commented on app/main/checks/report_checks/max_abstract_size_check.py
> +        abstract_size = main_page - abstract_page
напомните, что хранится по ключу в self.headers - просто страницы?

2023-11-27 12:25 UTC, HadronCollider commented on app/main/checks/report_checks/max_abstract_size_check.py
> +        if abstract_size > self.max_size:
Возможно стоит проверять их в один момент (в плане фидбека, чтобы не было "получил уведомление о реферате -> исправил реферат -> только потом узнал, что ещё и Abstract неверное")

2023-12-04 19:25 UTC, TheAnton1 commented on app/main/checks/report_checks/max_abstract_size_check.py
> +        abstract_size = main_page - abstract_page
Да, номера страниц, с которых начинается раздел

2023-12-04 19:35 UTC, TheAnton1 commented on app/main/checks/report_checks/max_abstract_size_check.py
> +        if abstract_size > self.max_size:
Исправил

2023-12-04 19:36 UTC, TheAnton1 commented on app/main/checks/report_checks/max_abstract_size_check.py
> +        self.max_size = 1
Исправил

2024-04-23 18:32 UTC, HadronCollider approved these changes

2024-04-23 18:32 UTC, merged