485 selenium test statistic
moevm/document_insight_system pull request #493
Opened 2024-01-22 11:39 UTC by MarinaProsche

Тест, проверяющий просмотр статистики согласно заданию
https://github.com/moevm/mse_auto_checking_slides_vaganov/issues/485

2024-02-07 15:10 UTC, MarinaProsche commented on tests/test_statistic.py
> +        password.send_keys(password_param)
Авторизация добавлена как метод в BasicSeleniumTest

2024-02-07 15:11 UTC, MarinaProsche commented on tests/README.md
> +webdriver-manager==4.0.1
добавлен tests/requirements.txt

2024-02-20 14:12 UTC, HadronCollider requested changes
Объедините, пожалуйста, с наработками https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/482

Плюс комментарий по тесту ниже

2024-02-20 14:12 UTC, HadronCollider commented on tests/test_statistic.py
> +        self.assertNotEquals(obj, None)
Я бы предложил усилить тест - проверить наличие строк в таблице (или их отсутствие, если проверок нет) - т.е. дождаться загрузки данных таблицы
- очень часто были случаи, что обработка запроса на получение статистики (т.е. данных о самих проверках, которые выводятся затем в таблице) ломалась, т.е. была вечная `Loading, please wait` - было бы хорошо, если этот (или другой тест) проверял бы этот момент

2024-02-21 14:10 UTC, MarinaProsche commented on tests/test_statistic.py
> +        self.assertNotEquals(obj, None)
Исправила.

2024-03-17 11:33 UTC, HadronCollider commented
Работа ведется в https://github.com/moevm/document_insight_system/pull/503

2024-03-17 11:33 UTC, closed without merging