Дополнение модели данных для хранения распарсенного текста
moevm/document_insight_system pull request #496
Opened 2024-02-04 16:42 UTC by blindsphynx

#469 

1. В класс `Check` добавлено поле `parsed_chapters` для хранения распарсенного текста ВКР в формате `{"header" : "", "start_page" : 1, "text" : ""}`
2. Добавлены функции `parse_headers_and_pages` и `parse_chapters` для соответствующего парсинга текста ВКР
3. Обработанный текст хранится в БД в коллекции checks

2024-03-12 22:32 UTC, HadronCollider requested changes

2024-03-12 22:32 UTC, HadronCollider commented on app/server.py
> +    parsed_file.parse()
Поскольку в систему загружаются разные виды/типы файлов (сейчас это и презентации, и doc-документы, и md-файлы) - парсинг файлгов происходит в отдельной функции, вам нужен раздел https://github.com/moevm/document_insight_system/blob/master/app/main/parser.py#L22

2024-03-12 22:32 UTC, HadronCollider commented on app/server.py
> +    chapters_with_headers = parse_headers_and_pages(chapters, parsed_file)
Не все docx-документы присылаемые в систему - VKR, тип документа определяется набором критериев (тип документа у отчета либо VKR либо LR) - поэтому parse_headers_and_pages для файла необходимо делать, видимо позднее, где известен тип документа (либо получать и проверять его)

Отсюда пара моментов
- кажется, что парсинг файла при загрузке файла сильно задержит весь процесс (и ожидания пользователя)
 - для проверок / парсинга содержимого используется отдельная задача / исполнитель (celery worker для celery-задачи, в которой как раз и производится проверка + парсинг: https://github.com/moevm/document_insight_system/blob/master/app/tasks.py#L37)

2024-03-12 22:32 UTC, HadronCollider commented on app/server.py
> +        'parsed_chapters': chapters_with_headers
Кажется, обсуждали с вами, что для обработанного текста и дальнейшей его токенизации (или что вы планируете) нужно завести отдельную коллекцию, а с учетом, что `checks` - хранит все проверки (не только ВКР), это становится ещё более актуальным

2024-04-19 13:28 UTC, blindsphynx commented on app/server.py
> +    parsed_file.parse()
убрала этот фрагмент, парсинг текста перенесён в create_task (см. последний коммит)

2024-04-19 13:36 UTC, blindsphynx commented on app/server.py
> +        'parsed_chapters': chapters_with_headers
1. создана новая коллекция `parsed_texts`, каждый документ в коллекции содержит `_id` проверки, имя файла и распарсенный по разделам и страницам текст

2. по поводу одинаковых файлов: при изменении внутри того же самого файла (таблицы, подписи и т. д.) нужно парсить имя этого файла, и если оно совпадает с новой проверкой, то обновлять текст в БД, а не загружать новый. если такой вариант подходит, в ближайшее время добавлю эту проверку

2025-04-11 08:39 UTC, closed without merging