515 separate calls of criteria try/except
moevm/document_insight_system pull request #518
Opened 2024-03-21 13:01 UTC by MarinaProsche

Добавлен try/except
Задача
https://github.com/moevm/document_insight_system/issues/515

2024-03-29 17:06 UTC, HadronCollider requested changes

2024-03-29 17:06 UTC, HadronCollider commented on app/root_logger.py
> +        self.setLevel(logging.ERROR)
Кажется, это лишнее: уровень логирования (https://docs.python.org/3/library/logging.html#logging-levels) устанавливает, логи какого уровня (и выше) будут логироваться 

Поэтому при включенном уровне DEBUG - будут логироваться от DEBUG до CRITICAL (а при включенном ERROR - только от ERROR до CRITICAL)

2024-03-29 17:06 UTC, HadronCollider commented on app/main/check_packs/base_criterion_pack.py
> +                criterion_check_result = {'score': 0, 'verdict': ('Во время проверки произошла ошибка, попробуйте чуть позже.')}
- Вынесите сообщение в верхние константы модуля (аналогично PRIORITY_CHECK_FAILED_MSG - что-нибудь по типу "unexpected check fail msg")
- Измените на `Во время проверки произошла ошибка, попробуйте позже или обратитесь к администратору систему`

2024-04-01 08:57 UTC, MarinaProsche commented on app/main/check_packs/base_criterion_pack.py
> +                criterion_check_result = {'score': 0, 'verdict': ('Во время проверки произошла ошибка, попробуйте чуть позже.')}
Исправила.

2024-04-01 08:57 UTC, MarinaProsche commented on app/root_logger.py
> +        self.setLevel(logging.ERROR)
Исправила.

2024-04-01 12:14 UTC, merged